baseURL = "/"
languageCode = "en-us"
title = "Daniel Wing"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    dateFormat = "6 January 2006"
    #
    # You can use either an image or text as logo.
    # To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
    # To use text as logo use 'logo_text'
    logo_text = "Daniel Wing"
    logo_alt = "logo"
    #logo_text = "logo_text"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "https://images.unsplash.com/photo-1532154066703-3973764c81fe?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=69dfab48990b309c73b2b29e604e2f02&auto=format&fit=crop&w=634&q=80"
        heading = "HI, I AM DANIEL WING AND I'M A"
        description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
        btn     = true
        btnText = "Visit my professional timeline"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "BODGER"
        [[params.banner.flipText]]
            title   = "LEARNER"
        [[params.banner.flipText]]
            title   = "KLUDGER"
        [[params.banner.flipText]]
            title   = "HUSBAND"
        [[params.banner.flipText]]
            title   = "CODER"
        [[params.banner.flipText]]
            title   = "PSYCHOLOGIST"
        [[params.banner.flipText]]
            title   = "INDUSTRIAL ENGINEER"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Footer section
    [params.footer]
        customized  = false # Set this variable to true if you customized the design.
        copyright_owner = "Themefisher"
        copyright_since = "2018"
        [[params.footer.social]]
            icon = "ion-social-facebook"
            link = "https://facebook.com"
        [[params.footer.social]]
            icon = "ion-social-twitter"
            link = "https://twitter.com"
        [[params.footer.social]]
            icon = "ion-social-linkedin"
            link = "https://linkedin.com"
        [[params.footer.social]]
            icon = "ion-social-googleplus"
            link = "https://googleplus.com"
        [[params.footer.social]]
            icon = "ion-social-github"
            link = "https://github.com"
    
